spring.application.name=rest-validacao

springdoc.api-docs.title= API de Tarefas do Capacita
springdoc.api-docs.description= Gerenciamento Inteligente de Tarefas
springdoc.api-docs.version=openapi_3_1
springdoc.swagger-ui.path=/docs


